
# Defaults, override in the site's [params.edgega].
[params.edgega]
	path   = "/a"
	region = "eu"
	debug  = false

[module.hugoVersion]
	min = "0.167.0"

[[module.mounts]]
	source = "assets"
	target = "assets"

[[module.mounts]]
	source = "cloudflare"
	target = "layouts/_partials/edgega/cloudflare"
	files  = ["*.html"]

[[module.mounts]]
	source = "cloudflare"
	target = "assets/edgega/cloudflare/js"
	files  = ["*.js"]

[[module.mounts]]
	source = "layouts"
	target = "layouts"
